### PR TITLE
Add Kafka Connect book

### PR DESCRIPTION
**Pull request by mimaison**
Adding the book about Kafka Connect I co-authored with Kate Stanley.

I followed the ["involved" steps](https://github.com/a-great-day-out-with/a-great-day-out-with.github.io#the-more-involved-way) but when I load the illustration in Excalidraw I get an extra outer border hence why the exported/generated SVGs are slightly larger. Is this expected or am I supposed to delete it?

### CODE REVIEW

**Comment by mimaison** [comment]
@gunnarmorling @hpgrahsl Do you still maintain this repo?

**Comment by hguerrero** [comment]
@mimaison is that the only change? the double border? 

Let's give some time to @gunnarmorling to reply. If he is not able I can merge the PR.

**Comment by mimaison** [comment]
My change is adding the Kafka Connect book. The double border is a side effect I caused making my change.

**Comment by gunnarmorling** [comment]
Hey, sorry for the super-late reply. Yes, @hpgrahsl and I still maintain this repo, we just didn't have an awful lot of time for it as of late. Will integrate this asap. Thanks for the nice addition, @mimaison!

**Comment by hpgrahsl** [comment]
Took me long but it's addressed in #33! THX again for the addition.

**Comment by mimaison** [comment]
Thanks!

**Comment by gunnarmorling** [comment]
Almost reached its one year anniversary ;)

**Pull request closed without merging**
